version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant/data:/qdrant/storage

  contextmore:
    image: prima101112/contextmores:latest
    container_name: contextmore
    platform: linux/amd64
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION_NAME=contextmore
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  qdrant_data:
